package ergo

import (
	"fmt"
	"time"

	"github.com/halturin/ergo/etf"
	"github.com/halturin/ergo/lib"
)

type GenSaga struct {
	GenServer
}

type GenSagaTransactionOptions struct {
	// Name defines the name of this transaction. By default
	// this name has autogenerated ID.
	Name string
	// HopLimit defines a number of hop within the transaction. Default limit
	// is 0 (no limit).
	HopLimit uint
	// Lifespan defines a lifespan for the transaction in seconds. Default 0 (no limit)
	Lifespan uint

	// TwoPhaseCommit enables 2PC for the transaction. This option makes all
	// Sagas involved in this transaction invoke HandleCommit callback once
	// the transaction is finished.
	TwoPhaseCommit bool
}

type GenSagaOptions struct {
	// MaxTransactions defines the limit for the number of active transactions. Default: 0 (unlimited)
	MaxTransactions uint
	// Worker
	Worker GenSagaWorkerBehavior
}

type GenSagaState struct {
	GenServerState
	Options GenSagaOptions
	txs     map[string]GenSagaTransaction

	// simple one for one supervisor for workers
	sv  *GenSagaWorkerSup
	svp *Process
}

type GenSagaTransaction struct {
	ID        string
	StartTime int64
	Options   GenSagaTransactionOptions
	Ref       etf.Ref
	Parents   []etf.Pid
	timer     time.Timer
	next      map[string]GenSagaNext
}

type GenSagaNext struct {
	// Next - etf.Pid, string (for the locally registered process), etf.Tuple{process, node} (for the remote process)
	Next interface{}
	// Value - a value for the invoking HandleNext on a Next hop.
	Value interface{}
	// Timeout - how long this Saga will be waiting for the result from the Next hop. Default - 10 seconds
	Timeout uint
}

type sagaMessage struct {
	Request string
	Pid     etf.Pid
	Command interface{}
}

type sagaMessageNext struct {
	Transaction GenSagaTransaction
	Value       interface{}
}

type sagaMessageResult struct {
	Transaction GenSagaTransaction
	From        etf.Pid
	Result      interface{}
}

type sagaMessageCancel struct {
	Transaction GenSagaTransaction
	From        etf.Pid
	Reason      string
}
type sagaSetMaxTransactions struct {
	max uint
}

// GenSagaBehavior interface
type GenSagaBehavior interface {
	//
	// Mandatory callbacks
	//

	// InitSaga
	InitSaga(state *GenSagaState, args ...interface{}) error

	// HandleNext
	HandleNext(state *GenSagaState, tx GenSagaTransaction, value interface{}) error

	// HandleCancel invoked on a request of transaction cancelation.
	HandleCancel(state *GenSagaState, tx GenSagaTransaction, reason string) error

	// HandleResult
	HandleResult(state *GenSagaState, tx GenSagaTransaction, next GenSagaNext, result interface{}) error

	// HandleTimeout
	HandleTimeout(state *GenSagaState, tx GenSagaTransaction, next GenSagaNext) error

	//
	// Optional callbacks
	//

	HandleJobResult(state *GenStageState, ref etf.Ref, result interface{}) error
	HandleJobInterim(state *GenStageState, ref etf.Ref, interim interface{}) error
	HandleJobFailed(state *GenStageState, ref etf.Ref) error

	// HandleInterim invoked if received interim result from the Next hop
	HandleInterim(state *GenSagaState, tx GenSagaTransaction, next GenSagaNext, interim interface{}) error
	// HandleCommit invoked if TwoPhaseCommit is enabled on the given transaction
	HandleCommit(state *GenSagaState, tx GenSagaTransaction)

	// HandleGenStageCall this callback is invoked on Process.Call. This method is optional
	// for the implementation
	HandleGenSagaCall(state *GenSagaState, from GenServerFrom, message etf.Term) (string, etf.Term)
	// HandleGenStageCast this callback is invoked on Process.Cast. This method is optional
	// for the implementation
	HandleGenSagaCast(state *GenSagaState, message etf.Term) string
	// HandleGenStageInfo this callback is invoked on Process.Send. This method is optional
	// for the implementation
	HandleGenSagaInfo(state *GenSagaState, message etf.Term) string
}

// SetMaxTransactions set maximum transactions fo the saga
func (gs *GenSaga) SetMaxTransactions(process *Process, max uint) error {
	message := sagaSetMaxTransactions{
		max: max,
	}
	_, err := process.Direct(message)
	return err
}

func StartSagaTransaction(process *Process, options GenSagaTransactionOptions, next GenSagaNext) etf.Ref {
	if options.Name == "" {
		options.Name = lib.RandomString(32)
	}

	ref := process.MonitorProcess(next.Next)
	tx := GenSagaTransaction{
		ID:        options.Name,
		Options:   options,
		StartTime: time.Now().Unix(),
		Ref:       ref,
	}

	message := etf.Tuple{
		etf.Atom("$saga_next"),
		process.Self(),
		etf.Tuple{tx, next.Value},
	}

	process.Send(next.Next, message)

	return tx.Ref
}

// default GenSaga callbacks

func (gs *GenSaga) HandleInterim(state *GenSagaState, tx GenSagaTransaction, interim interface{}) error {
	// default callback if it wasn't implemented
	fmt.Printf("HandleInterim: unhandled message %#v\n", tx)
	return nil
}

func (gs *GenSaga) HandleCommit(state *GenSagaState, tx GenSagaTransaction) {
	return
}

func (gs *GenSaga) HandleGenSagaCall(state *GenSagaState, from GenServerFrom, message etf.Term) (string, etf.Term) {
	// default callback if it wasn't implemented
	fmt.Printf("HandleGenSagaCall: unhandled message (from %#v) %#v\n", from, message)
	return "reply", etf.Atom("ok")
}

func (gs *GenSaga) HandleGenSagaCast(state *GenSagaState, message etf.Term) string {
	// default callback if it wasn't implemented
	fmt.Printf("HandleGenSagaCast: unhandled message %#v\n", message)
	return "noreply"
}
func (gs *GenSaga) HandleGenSagaInfo(state *GenSagaState, message etf.Term) string {
	// default callback if it wasn't implemnted
	fmt.Printf("HandleGenSagaInfo: unhandled message %#v\n", message)
	return "noreply"
}

//
// GenServer callbacks
//
func (gs *GenSaga) Init(state *GenServerState, args ...interface{}) error {
	var options GenSagaOptions
	if opts, ok := args[0].(GenSagaOptions); ok {
		options = opts
	}
	sagaState := &GenSagaState{
		GenServerState: *state,
		txs:            make(map[string]GenSagaTransaction),
	}
	if err := state.Process.GetObject().(GenSagaBehavior).InitSaga(sagaState, args...); err != nil {
		return err
	}
	state.State = sagaState

	if options.Worker == nil {
		// Do not start supervisor if Worker hasn't been defined
		return nil
	}

	// start supervisor
	svopts := GenSagaWorkerSupOptions{
		Worker: options.Worker,
	}
	sv := &GenSagaWorkerSup{}
	svp, err := state.Process.Node.Spawn("gen_saga_worker_sup", ProcessOptions{}, sv, svopts)
	if err != nil {
		return err
	}

	state.Process.Link(svp.Self())
	sagaState.sv = sv
	sagaState.svp = svp

	return nil
}

func (gs *GenSaga) HandleCall(state *GenServerState, from GenServerFrom, message etf.Term) (string, etf.Term) {
	st := state.State.(*GenSagaState)
	return state.Process.GetObject().(GenSagaBehavior).HandleGenSagaCall(st, from, message)
}

func (gs *GenSaga) HandleDirect(state *GenServerState, message interface{}) (interface{}, error) {
	st := state.State.(*GenSagaState)
	switch m := message.(type) {
	case sagaSetMaxTransactions:
		st.Options.MaxTransactions = m.max
		return nil, nil
	default:
		return nil, ErrUnsupportedRequest
	}
}

func (gs *GenSaga) HandleCast(state *GenServerState, message etf.Term) string {
	st := state.State.(*GenSagaState)
	return state.Process.GetObject().(GenSagaBehavior).HandleGenSagaCast(st, message)
}

func (gs *GenSaga) HandleInfo(state *GenServerState, message etf.Term) string {
	var m sagaMessage

	st := state.State.(*GenSagaState)
	// check if we got a 'DOWN' message
	// {DOWN, Ref, process, PidOrName, Reason}
	if isDown, d := IsDownMessage(message); isDown {
		if err := handleSagaDown(st, d); err != nil {
			return err.Error()
		}
		return "noreply"
	}

	if err := etf.TermIntoStruct(message, &m); err != nil {
		reply := state.Process.GetObject().(GenSagaBehavior).HandleGenSagaInfo(st, message)
		return reply
	}

	err := handleSagaRequest(st, m)
	switch err {
	case nil:
		return "noreply"
	case ErrStop:
		return "stop"
	case ErrUnsupportedRequest:
		reply := state.Process.GetObject().(GenSagaBehavior).HandleGenSagaInfo(st, message)
		return reply
	default:
		return err.Error()
	}
}

func handleSagaRequest(state *GenSagaState, m sagaMessage) error {
	var nextMessage sagaMessageNext
	var cancel sagaMessageCancel
	var result sagaMessageResult

	next := GenSagaNext{}
	switch m.Request {
	case "$saga_next":
		if err := etf.TermIntoStruct(m.Command, &nextMessage); err != nil {
			return ErrUnsupportedRequest
		}

		// Check for the loop
		if _, ok := state.txs[nextMessage.Transaction.ID]; ok {
			cancel := etf.Tuple{
				etf.Atom("$saga_cancel"),
				nextMessage.Transaction.Ref,
				nextMessage.Transaction.ID,
				"loop_detected",
			}
			state.Process.Send(m.Pid, cancel)
			return nil
		}

		// Check if exceed the number of transaction on this saga
		if len(state.txs)+1 > int(state.Options.MaxTransactions) {
			cancel := etf.Tuple{
				etf.Atom("$saga_cancel"),
				nextMessage.Transaction.Ref,
				nextMessage.Transaction.ID,
				"exceed_max_limit",
			}
			state.Process.Send(m.Pid, cancel)
			return nil
		}

		// Check if exceed hop limit
		hop := len(nextMessage.Transaction.Parents)
		hoplimit := nextMessage.Transaction.Options.HopLimit
		if hoplimit > 0 && hop+1 > int(hoplimit) {
			cancel := etf.Tuple{
				etf.Atom("$saga_cancel"),
				nextMessage.Transaction.Ref,
				nextMessage.Transaction.ID,
				"exceed_hop_limit",
			}
			state.Process.Send(m.Pid, cancel)
			return nil
		}

		// Check if lifespan is limited and transaction is too long
		lifespan := nextMessage.Transaction.Options.Lifespan
		l := time.Now().Unix() - nextMessage.Transaction.StartTime
		if lifespan > 0 && l > int64(lifespan) {
			cancel := etf.Tuple{
				etf.Atom("$saga_cancel"),
				nextMessage.Transaction.Ref,
				nextMessage.Transaction.ID,
				"exceed_lifespan",
			}
			state.Process.Send(m.Pid, cancel)
			return nil
		}

		// everything looks good. go further
		state.txs[nextMessage.Transaction.ID] = nextMessage.Transaction

		//code, value := state.Process.GetObject().(GenSagaBehavior).HandleNext(state, nextMessage.Transaction, next.Value)
		//switch code {
		//case "result":
		//case "interim":
		//case "next":
		//case "wait":

		//case "cancel":
		//	cancel := etf.Tuple{
		//		etf.Atom("$saga_cancel"),
		//		nextMessage.Transaction.Ref,
		//		nextMessage.Transaction.ID,
		//		value,
		//	}
		//	state.Process.Send(nextMessage.Pid, cancel)
		//	return nil
		//case "stop":
		//	return ErrStop
		//default:
		//	return fmt.Errorf(code)
		//}
		return nil
	case "$saga_cancel":
		if err := etf.TermIntoStruct(m.Command, &cancel); err != nil {
			return ErrUnsupportedRequest
		}
		state.Process.GetObject().(GenSagaBehavior).HandleCancel(state, cancel.Transaction, cancel.Reason)
		return nil
	case "$saga_interim":
		if err := etf.TermIntoStruct(m.Command, &result); err != nil {
			return ErrUnsupportedRequest
		}
		state.Process.GetObject().(GenSagaBehavior).HandleInterim(state, result.Transaction, next, result.Result)
		return nil
	case "$saga_result":
		if err := etf.TermIntoStruct(m.Command, &result); err != nil {
			return ErrUnsupportedRequest
		}
		state.Process.GetObject().(GenSagaBehavior).HandleResult(state, result.Transaction, next, result.Result)
		return nil
	}
	return ErrUnsupportedRequest
}
func handleSagaDown(state *GenSagaState, down DownMessage) error {
	return nil
}

// default callbacks

func (gs *GenSaga) HandleJobResult(state *GenStageState, ref etf.Ref, result interface{}) error {
	fmt.Printf("HandleJobResult: unhandled message %#v\n", result)
	return nil
}
func (gs *GenSaga) HandleJobInterim(state *GenStageState, ref etf.Ref, interim interface{}) error {
	fmt.Printf("HandleJobInterim: unhandled message %#v\n", interim)
	return nil
}
func (gs *GenSaga) HandleJobFailed(state *GenStageState, ref etf.Ref) error {
	fmt.Printf("HandleJobFailed: unhandled message %#v\n", ref)
	return nil
}
